### ISSUE TITLE
"# define" is not highlighted correctly.

### ISSUE THREAD

**Issue by 1-p** [skx/kilua#12]
If one put spaces between `#` and `define` it should still be treated as `#define`.

**Comment by skx** [comment]
It should, but unfortunately the keywords are treated as literal matches - with the exception of the special handling for `|` - so "`#   define`" and "`#define`" _are_ different, and thus the match fails.

The only sane solution would be to define the token as "`#\s*define`" and use a regular expression library, such as PCRE, to do the matching.

Adding another library would spoil the simplicity of the editor. I'm not **entirely** averse to using other libraries, as indeed I've added lua, but I think I'd want a stronger justification than this specific failure-case.
