### ISSUE TITLE
Deleting a lot of characters causes corruption.

### ISSUE THREAD

**Issue by skx** [skx/kilua#15]
The following code seems to result in corruption:

```
  function steve()
     end_of_file()
     local c = 10000
     while( c > 1 ) do
        c = c -1
        delete();
     end
  end
```

This was actually found via "HOME Ctrl-space END Ctrl-w" (i.e. select who file, and then Ctrl-w to cut).  But it turns out deleting a single character, 10,000 times, is sufficient to cause corruption.

**Comment by skx** [comment]
OK with the previous commit we can now reliably trigger this corruption.

Append this to `kilo.lua`:

```
  --
  -- Cause corruption.
  --
  function on_init()
     -- Create an input-file
     os.execute( "cp kilo.c kilo.c.tmp" )

     -- Open it
     open( "kilo.c.tmp" )

     -- Move to end of file
     end_of_file()

     -- Delete a lot of lines.
     local c = 10000
     while( c > 1 ) do
        c = c -1
        delete();
     end

     -- All done
     --exit()
  end
```

Now launch:

```
   ./kilo /dev/null --eval=on_init
```

Immediately the display is corrupt.  

TODO:
- Add `exit()`
- Run under valgrind.

**Comment by skx** [comment]
Current state of this bug - still present.

To reproduce:

```
  ./kilo --config ./valgrind.lua /dev/null  --eval=valgrind
```

This:
- Loads the additional Lua configuration-file `valgrind.lua`
- Opens the file /dev/null for editing (!)
- Invokes `function valgrind()` on startup.

Running `make valgrind; Ctrl-q Ctrl-q Ctrl-q ; less valgrind.out` shows the output from valgrind.

I've traced through the code several times, and reverted the contents of `editorUpdateSyntax`, `editorUpdateRow` and a few more functions to @antirez's original implementation but still the bug appears.

The code _seems_ to be correct, but I'm 90% sure there is a subtle off by one, or other corruption bug in `editorDeleteRow`.  This is suspicious to me:

```
editorUpdateRow(row);
row->size--;
```

Surely size should be decreased **before** the row is updated?    Anyway reversing that order doesn't help.

Will ponder some more.  Would be nice if this could be confirmed as a bug in the original program, rather than something I've introduced too!

**Comment by skx** [comment]
Ahah.

The problem **isn't** corruption, per se.  The problem is entirely rendering.

To reproduce:

```
   $ make && ./kilo  --config ./valgrind.lua --eval valgrind /dev/null
```

At this point the editor will be open, and it will show gibberish.
- Pressing "up" or "page-up" will continue to show gibberish.

BUT:
- Press "HOME" or "END" and you see all is actually OK.

The problem must be that we're not updating the screen-position correctly, somewhere.

To resolve we can change `delete_lua` to add the current display offset, etc:

```
        editorSetStatusMessage("x=%d,y=%d", E.cx, E.cy );  // add colloff + rowoff + & etc.
```

Now I feel better.

**Comment by skx** [comment]
Added some debugging before I left for work.

`E.colloff` becomes negative, after the `valgrind` function runs, which is the root cause for the display corruption.  It also explains why pressing `HOME` or `END` reinstates the display, because they indirectly reset the row/col offsets.

**Comment by 1-p** [comment]
I tried to reproduce this in original kilo (i.e. the one by antirez) and failed. `E.coloff` doesn't become negative.

(called `editorDelChar` 10,000 and 100,000 times, doesn't seem to cause problem.)

**Comment by skx** [comment]
Yeah I couldn't reproduce it in the original either.

There are only two places in the code where `E.coloff` is decremented, and both look sane to me.  I have a fix:

```
 @@ -1613,6 +1613,15 @@ int delete_lua(lua_State *L)
              E.cx--;
      }

 +    /*
 +     * BUGFIX: Ensure we don't walk off the screen,
 +     * and draw gibberish.
 +     */
 +    if ( E.coloff < 0 )
 +        E.coloff = 0;
 +    if ( E.rowoff < 0 )
 +        E.rowoff = 0;
 +
 if (row) editorUpdateRow(row);
```

But I'd like to understand how it is getting into this state first.

**Comment by skx** [comment]
This is where it all goes wrong:

```
    if (E.cx >= E.screencols)
    {
        int shift = (E.screencols - E.cx) + 1;
        E.cx -= shift;
        E.coloff += shift;

        editorSetStatusMessage( "Shift is %d", shift );
    }
```

The status message shows "Shift is -2".
