### ISSUE TITLE
BREAKING: We should change the config-loading.

### ISSUE THREAD

**Issue by skx** [skx/kilua#27]
Rather than load:
- `~/.kilua.lua`
- `./kilua.lua`

We should load:
- `~/.kilua/init.lua`
- If it exists ~/.kilua/$(hostname).lua`

We should no longer load from the pwd/cwd - it is a security-risk.

**Comment by sdegutis** [comment]
Loading from pwd/cwd is indeed a bad idea, but `kilua.lua` belongs as part of the project. You should rather add a step to the build phase, which creates a C file based on the Lua script, containing the Lua script as an exported C string, and use that string from inside the main C code. That way you can distribute the binary anywhere, and it'll Just Work™.

**Comment by skx** [comment]
Thanks for the suggestion, I'll do exactly that.

(Funny you mention that approach, that's exactly what I was going to do for the welcome-message, but it didn't cross my mind to do the same thing for the Lua config-file".)

**Comment by sdegutis** [comment]
@skx Interesting how you solved it. I was thinking something closer to sdegutis/kilo@6468483273b45b4abcebb90b82456509ddbe81c8. Why not go that route instead?

**Comment by skx** [comment]
Just because I had something similar in place for the `welcome.txt` -> `welcome.h` and it always seems natural to use Perl for things like this.
