### ISSUE TITLE
Consider using ncurses.

### ISSUE THREAD

**Issue by skx** [skx/kilua#40]
Although that's against the spirit of the original project I think it's still somewhat reasonable.
- The current display loop currently is a mess.
- Conceptually it is simple:
  - Move to 0,0
  - For each visible row in the text - draw it
  - Handle colours via hardwired escape-sequences
  - Show the cursor.

Using `ncursesw` our loop would be equivalent in functionality:
- For each row that is visible
  - Move to (row,0) and draw the string, setting colours appropriately.

Pros:
- We'd be more portable (to terminals, rather htan systems).
- We'd also be able to use `keyname` to perform the key-expansion in C.
- We could handle Unicode input.

Cons:
- Added dependency.
- More significant code-churn and divergence - though at this point reconciling changes is almost impossible.

I'm not going to hack on this immediately, but I think it's probably something that will happen sooner or later..

**Comment by sdegutis** [comment]
Meh, all modern terminals use the same vt escape codes. But you would benefit from not having to redraw the entire screen on every change. My plan was to scan for "dirty" regions of the active buffer(s), and redraw only those areas. Although maybe that's pre-mature optimization, and maybe it's never going to be too slow to redraw everything. Then again, I'm already thinking with split-panes and a tab bar (etc.) in mind. So I'm probably getting ahead of myself.

**Comment by skx** [comment]
As per last updates on #49 this is .. abandoned.
