### ISSUE TITLE
The status-bar should be set by Lua.

### ISSUE THREAD

**Issue by skx** [skx/kilua#41]
At the moment the status-bar looks something like this:

```
 File 2/2: <NONE>          ...    Col:1 Row:1/0
```

If that was populated by a call to `get_status()` then it could be updated to show things like:
- The current date/time.
- The size of the buffer.
- The number of words in the buffer.
- Anything else the user wanted.

Suggest we leave the default but only use it if the callback function doesn't exist.

**Comment by sdegutis** [comment]
How will you manage the idea of having a right/left side? Will there be two functions? Or will the one function return two values? What happens if they overlap (because the window is resized so tiny)?

**Comment by skx** [comment]
I expect to mirror the C-code:
- The Lua function will be called.
  - It will have "`local left = ...`"
  - It will have "`local right = ..`"
  - At the end of the function if both strings are summed and are smaller than the width of the console they will have spaces added in the middle.
  - If the strings, combined, are larger than the width of the console then it will be truncated.

In short I expect the status-bar function to return a _single_ string, containing everything that will fit.  And that string will be 100% of the width, wether it is padded in the middle, or truncated.

**Comment by skx** [comment]
(And this is why I ~~expected~~ exported the `width()` function - so that the lua callback could make the right decision.)
